### ISSUE TITLE
Trying to create a MsgVpn using the example, getting a problem with alias.

### ISSUE THREAD

**Issue by spierepf** [SolaceSamples/solace-samples-java-jcsmp#64] opened 2020-08-06 17:53 UTC
I am trying to programmatically create a `MsgVpn` using Java. I've written a small JUnit5 test using some example code that I found in this github.

The test spins up a docker container running `solace/solace-pubsub-standard` with some basic credentials, and then `initialize()`s a `sempApiInstance`, and uses it to `createMessageVpn()` just as the example code at https://github.com/SolaceSamples/solace-samples-semp/blob/master/java/src/main/java/com/solace/samples/ManageVPN.java does.

However, instead of getting a `MsgVpnResponse` I get an exception. It appears to be looking for an alias, but I'm not sure what that is precisely, or what value to provide.

Here is the exception:

```
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{
    "meta":{
        "error":{
            "code":11,
            "description":"Problem with alias: Got value `None` of type `null`. Value must be of type(s): `('string',)`",
            "status":"INVALID_PARAMETER"
        },
        "request":{
            "method":"POST",
            "uri":"http://localhost:32825/SEMP/v2/config/msgVpns"
        },
        "responseCode":400
    }
}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:651)
	at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:512)
	at io.swagger.client.api.MsgVpnApi.createMsgVpn(MsgVpnApi.java:211)
	at com.example.demo.CreateNewMessageVpnTests.createMessageVpn(CreateNewMessageVpnTests.java:50)
	at com.example.demo.CreateNewMessageVpnTests.test(CreateNewMessageVpnTests.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

And here is my JUnit5 Test

```
package com.example.demo;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.web.client.RestClientException;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import io.swagger.client.ApiClient;
import io.swagger.client.api.MsgVpnApi;
import io.swagger.client.model.MsgVpn;
import io.swagger.client.model.MsgVpn.AuthenticationBasicTypeEnum;
import io.swagger.client.model.MsgVpnResponse;

@SpringBootTest
@Testcontainers
class CreateNewMessageVpnTests {
    @SuppressWarnings("rawtypes")
    @Container
    public GenericContainer solace = new GenericContainer("solace/solace-pubsub-standard")
            .withEnv("username_admin_globalaccesslevel", "admin").withEnv("username_admin_password", "admin")
            .withSharedMemorySize(2L * 1024L * 1024L * 1024L).withExposedPorts(55555, 8080);

    MsgVpnApi sempApiInstance;

    public void initialize(String basePath, String user, String password) throws Exception {

        System.out.format("SEMP initializing: %s, %s \n", basePath, user);

        ApiClient thisClient = new ApiClient();
        thisClient.setBasePath(basePath);
        thisClient.setUsername(user);
        thisClient.setPassword(password);
        sempApiInstance = new MsgVpnApi(thisClient);
    }

    public MsgVpnResponse createMessageVpn(String messageVpnName) throws RestClientException {

        System.out.format("Creating Message-VPN: %s...\n", messageVpnName);

        // Create message-vpn
        MsgVpn msgVpn = new MsgVpn();
        msgVpn.setMsgVpnName(messageVpnName);
        msgVpn.setAuthenticationBasicType(AuthenticationBasicTypeEnum.INTERNAL);
        msgVpn.setMaxMsgSpoolUsage(1500L);
        msgVpn.setEnabled(true);
        MsgVpnResponse resp = sempApiInstance.createMsgVpn(msgVpn, null, null);

        return resp;
    }

    @Test
    void test() throws Exception {
        initialize(String.format("http://%s:%d/SEMP/v2/config", solace.getHost(), solace.getMappedPort(8080)), "admin",
                "admin");
        MsgVpnResponse msgVpnResponse = createMessageVpn("messageVpnName");
    }

}
```

**Comment by Mrc0113** [comment] 2020-08-06 19:19
Hi @spierepf, 

That is interesting. Per the docs an `alias` shouldn't be required. 

This is essentially using SEMP, which is our management REST API to create the vpn. The [SEMP Developer Docs](https://docs.solace.com/API-Developer-Online-Ref-Documentation/swagger-ui/config/index.html#/msgVpn/createMsgVpn) have a pretty good description of all the options available. I tested locally against my docker container using postman and it worked successfully without the alias. Do you mind trying to set alias to an empty string and seeing if it works or if you get a different error? Also what broker version are you using? 

![image](https://user-images.githubusercontent.com/1815312/89572912-ce85f180-d7f7-11ea-8298-c314885ed185.png)

**Comment by spierepf** [comment] 2020-08-07 02:56
I tried setting the alias to the empty string, but it just complained about authenticationBasicEnabled, and when I set that to false, it just complained about authenticationBasicProfileName...

I am using version 9.6.0.27:

```
$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
solace-pubsub-standard          9.6.0.27            3948c89d28b9        3 weeks ago         959MB
solace/solace-pubsub-standard   latest              3948c89d28b9        3 weeks ago         959MB
testcontainersofficial/ryuk     0.3.0               344c0229fe44        2 months ago        12MB
```

I've also uploaded my code to github at https://github.com/spierepf/solace-junit5-test

**Comment by Mrc0113** [comment] 2020-08-07 20:12
@bczoma, do you happen to know why it's forcing every optional configuration to be specified?

**Comment by bczoma** [comment] 2020-08-07 20:36
Was the Java SEMP client library recently created as documented at https://solace.com/samples/solace-samples-semp/generate-semp-client-lib ?

**Comment by spierepf** [comment] 2020-08-07 21:26
I'm creating the Java SEMP client library using the `swagger-codegen-maven-plugin`. If you look at the github repo I posted earlier, you can see the config in the pom.xml file.

**Comment by Mrc0113** [comment] 2020-08-10 21:13
Hi @spierepf, 

After chatting with a few folks I believe the issue is that the generated library is passing "null" instead of omitting undefined properties from the request. SEMPv2 apparently does not expect to receive "null" for values that are not specified. 

So maybe there is a way in swagger-codegen to prevent this from happening?

**Comment by Mrc0113** [comment] 2020-08-13 17:02
@spierepf, Thank you for opening the issue in the swagger-codegen repo. I'm also pinging some folks internally to see if we have a known work around for this as it obviously worked at some point

**Comment by Mrc0113** [comment] 2020-08-26 21:05
Hi @spierepf, I unfortunately haven't gotten a chance to circle back to this myself, but did the suggestion that was made in https://github.com/swagger-api/swagger-codegen/issues/10426 solve the issue for you?

**Comment by aaron-613** [comment] 2022-02-06 12:46
Should we close this?  Been 1.5 years.  And is in wrong repo..?

**Comment by Mrc0113** [comment] 2022-02-07 14:54
Closing.

**Closed by Mrc0113** 2022-02-07 14:54 UTC
